### ISSUE TITLE
Specify minimum required version of Matlab

### ISSUE THREAD

**Issue by alexdewar** [djmaxus/matlab-repo-init#13]

**Comment by djmaxus** [comment]
At the moment, it is specified in the [workflow configuration](https://github.com/djmaxus/matlab-repo-init/blob/60aa42c682684df1e63ebae397034320cad79b17/.github/workflows/matlab-ci.yml) only:

```yml
- uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
``` 

Do you think it is worth mentioning somewhere in README or documentation?
